import pyautogui 
import time
import psutil

def wait():
    time.sleep(0.5)
print("Welcome to task automator!!!")
print("1. Create a new python file for a new python project\n" + "2. Automate an E-mail using G-mail\n" + "3. Send a whatsapp message\n" + "4. Search something in Youtube")
print("5. Send a Discord message\n" + "6. Automate System Health Checks\n" + "7. Ask questions from ChatGPT or Copilot web or Windows Copilot")

choice = input("Please type the number of the option you want to choose: ")

if choice == "1":
    name_file = input("Please type the name of the file you want to create: ")
    print("I am creating a new python file....")
    time.sleep(1)
    pyautogui.hotkey('win', '1')
    time.sleep(3.5)
    pyautogui.moveTo(92, 759)
    wait()
    pyautogui.leftClick()
    time.sleep(1)
    pyautogui.moveTo(332, 621)
    wait()
    pyautogui.doubleClick()
    wait()
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('enter')
    wait()
    pyautogui.moveTo(1222, 321)
    pyautogui.rightClick()
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('enter')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('down')
    pyautogui.press('enter')
    wait()
    pyautogui.write(name_file)
    pyautogui.press('right')
    pyautogui.press('right')
    pyautogui.press('right')
    pyautogui.press('right')
    pyautogui.press('backspace')
    pyautogui.press('backspace')
    pyautogui.press('backspace')
    wait()
    pyautogui.write("py")
    wait()
    pyautogui.press('enter')
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.hotkey('win', '1')
    print("I created a new python file called " + name_file + ".py")

elif choice == "2":
    print("Example: name@gmail.com")
    gmail_person = input("Please type the name of the G-mail account you want to automate: ")
    gmail_subject = input("Please type the subject of the email you want to send: ")
    gmail_message = input("Please type the message you want to send: ")
    print("Ok now I am going to automate an E-mail using G-mail")
    time.sleep(2)
    pyautogui.press('win')
    wait()
    pyautogui.write('Microsoft Edge')
    wait()
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.write("https://mail.google.com/mail/u/1/#inbox")
    wait()
    pyautogui.press('enter')
    time.sleep(10)
    pyautogui.moveTo(125, 180)
    wait()
    pyautogui.leftClick()#Compose
    wait()
    pyautogui.write(gmail_person)
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.moveTo(1085, 435)
    wait()
    pyautogui.leftClick()#Subject
    wait() 
    pyautogui.write(gmail_subject)
    wait()
    pyautogui.moveTo(1156, 501)
    wait()
    pyautogui.leftClick()#Message
    wait()
    pyautogui.write(gmail_message)
    wait()
    pyautogui.moveTo(976, 804)
    wait()
    pyautogui.leftClick()#Send
    wait()
    pyautogui.hotkey('win', '2')
    wait()
    print("I sent an E-mail to: " + gmail_person + "\nWith the subject: " + gmail_subject)

elif choice == "3":
    who_person = input("Please type the name of the person or group name you want to send a whatsapp message to: ")
    message = input("Please type the message you want to send: ")
    print("Ok now I am going to send a whatsapp message to: " + who_person)
    time.sleep(2)
    pyautogui.hotkey('win', '2')
    wait()
    pyautogui.hotkey('ctrl', 't')
    wait()
    pyautogui.write("https://web.whatsapp.com/")
    wait()
    pyautogui.press('enter')
    time.sleep(15)
    pyautogui.moveTo(228, 181)
    wait()
    pyautogui.leftClick()
    wait()
    pyautogui.write(who_person)
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.write(message)
    wait()
    pyautogui.press('enter')    
    wait()
    pyautogui.hotkey('win', '2')
    print("I sent a whatsapp message to: " + who_person)

elif choice == "4":
    search = input("Please type the search you want to do: ")
    print("Ok now I am going to search: " + search)
    time.sleep(2)
    pyautogui.hotkey('win', '2')
    wait()
    pyautogui.hotkey('ctrl', 't')
    wait()
    pyautogui.write("https://www.youtube.com/")
    wait()
    pyautogui.press('enter')
    time.sleep(10)
    pyautogui.typewrite('/')
    time.sleep(1)
    pyautogui.write(search)
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.hotkey('win', '2')
    print("I searched: " + search)
    time.sleep(2)
    pyautogui.hotkey('win', '2')

elif choice == "5":
    who_person = input("Please type the name of the person or group name you want to send a Discord message to: ")
    message = input("Please type the message you want to send: ")
    print("Ok now I am going to send a Discord message to: " + who_person)
    time.sleep(2)
    pyautogui.hotkey('win', '2')
    wait()
    pyautogui.hotkey('ctrl', 't')
    wait()
    pyautogui.write("https://discord.com/channels/@me")
    wait()
    pyautogui.press('enter')
    time.sleep(10)
    pyautogui.moveTo(204, 109)
    wait()
    pyautogui.leftClick()
    wait()
    pyautogui.write(who_person)
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.moveTo(666, 797)
    wait()
    pyautogui.leftClick()
    wait()
    pyautogui.write(message)
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.hotkey('win', '2')
    print("I sent a Discord message to: " + who_person + "!\n" + "Stating the message: " + message)

elif choice == '6':
    print("Checking for system usage...")
    time.sleep(2)
    threshold = 75
    cpu_pct = psutil.cpu_percent()
    ram = psutil.virtual_memory()
    ram_percent = ram.percent
    print("Current CPU usage: {}%".format(cpu_pct))
    print("Current RAM usage: {}%".format(ram_percent))
    time.sleep(3)
    if cpu_pct > threshold:
        print("CPU usage is above 75%!\n" + "Too much usage!!\n" + "Current: {}%".format(cpu_pct))
    if ram_percent > 80:
        print("RAM usage too high!!!", ram_percent + "%")
    print("Deleting temporary files...")
    time.sleep(3)
    pyautogui.hotkey('win', 'r')
    wait()
    pyautogui.write("temp")
    wait()
    pyautogui.press('enter')
    wait()
    time.sleep(4)
    pyautogui.hotkey('ctrl','a')
    wait()
    pyautogui.hotkey('shift', 'delete')
    wait()
    pyautogui.press('enter')
    time.sleep(3)
    pyautogui.press('up')
    wait()
    pyautogui.press('enter')
    wait()
    pyautogui.press('down')
    wait()
    pyautogui.press('right')
    wait()
    pyautogui.press('enter')
    wait()
    time.sleep(3)
    pyautogui.hotkey('win','1')
    wait()
    print("System optimization complete!")

elif choice == '7':
    print("1. ChatGPT\n" + "2. Copilot Web\n" + "3. Windows Copilot") 
    bot_choice = input("Please type the number of the bot you want to choose: ")
    if bot_choice == '1':
        question = input("Please type the question you want to ask: ")
        print("Ok now I am going to ask a question using ChatGPT")
        time.sleep(2)
        pyautogui.hotkey('win', '2')
        wait()
        pyautogui.hotkey('ctrl', 't')
        wait()
        pyautogui.write("https://chat.openai.com")
        wait()
        pyautogui.press('enter')
        time.sleep(10)
        pyautogui.moveTo(857, 778)
        wait()
        pyautogui.leftClick()
        wait()
        pyautogui.write(question)
        wait()
        pyautogui.press('enter')
        wait()
        pyautogui.hotkey('win', '2')
        print("I asked a question using ChatGPT: " + question)
        time.sleep(2)
        pyautogui.hotkey('win', '2')

    elif bot_choice == '2':
        question = input("Please type the question you want to ask: ")
        print("Ok now I am going to ask a question using Copilot Web")
        time.sleep(2)
        pyautogui.hotkey('win', '2')
        wait()
        pyautogui.hotkey('ctrl', 't')
        wait()
        pyautogui.write("https://copilot.microsoft.com/")
        wait()
        pyautogui.press('enter')
        time.sleep(10)
        pyautogui.moveTo(857, 778)
        wait()
        pyautogui.leftClick()
        wait()
        pyautogui.write(question)
        wait()
        pyautogui.press('enter')
        wait()
        pyautogui.hotkey('win', '2')
        print("I asked a question using Copilot Web: " + question)
        time.sleep(2)
        pyautogui.hotkey('win', '2')

    elif bot_choice == '3':
        question = input("Please type the question you want to ask: ")
        print("Ok now I am going to ask a question using Windows Copilot")
        time.sleep(2)
        pyautogui.hotkey('win', 'c')
        time.sleep(3)
        pyautogui.write(question)
        wait()
        pyautogui.press('enter')
        wait()
        pyautogui.hotkey('win', 'c')
        print("I asked a question using Windows Copilot: " + question)
        time.sleep(2)
        pyautogui.hotkey('win', 'c')